- name: Copy files to Web Server
        shell: pwsh
        run: |
          # On définit les variables pour plus de clarté
          $key = ".vagrant/machines/firewall/virtualbox/private_key"
          
          # On crée le dossier de destination au cas où
          ssh -o StrictHostKeyChecking=no -p 2222 -i $key vagrant@127.0.0.1 "mkdir -p /home/vagrant/app"
          
          # On copie le code (On exclut les dossiers lourds pour gagner du temps)
          scp -r -o StrictHostKeyChecking=no -P 2222 -i $key ./index.js ./package.json vagrant@127.0.0.1:/home/vagrant/app/